GET http://localhost:5001/

### GET
GET http://localhost:5001/users/

### GET
GET http://localhost:5001/reserva/A00833416

### POST
POST http://localhost:5001/reserva/creareserva
Content-Type: application/json

{
    "id_sala": 5,
    "id_proyecto": 5,
    "lider_reserva": "A00833416",
    "fecha_generada": "2024-04-12",
    "dia_reserva": "2024-04-21",
    "hora_inicio": "10:00",
    "hora_final": "12:00"
}

###
POST http://localhost:5001/reserva/creareservachat
content-type: application/json

{
    "id_sala": "1",
    "id_proyecto": "2",
    "lider_reserva":"A00832807",
    "dia_reserva":"2024-04-10",
    "hora_inicio":"16:00:00.0000000",
    "hora_final":"17:00:00.0000000"
}




###
POST https://apidream.azurewebsites.net/reserva/creareserva
content-type: application/json

{
    "id_sala": "1",
    "id_proyecto": "2",
    "lider_reserva":"A00832807",
    "dia_reserva":"2024-04-10",
    "hora_inicio":"16:00:00.0000000",
    "hora_final":"17:00:00.0000000",
    "dispositivos":"",
    "integrantes": [{"matricula": "A00833968"}]
}

### GET
GET http://localhost:5001/proyecto/A00832807

### Delete
DELETE https://apidream.azurewebsites.net/reserva/cancelarreserva/61

### Get
GET http://localhost:5001/reserva/A00832807

###
GET https://apidream.azurewebsites.net/admin/reserva-proxima